global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-couchbase
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-couchbase-master:
    parameter_input: quickstart-couchbase-master.json
    template_file: quickstart-couchbase-master.template
  quickstart-couchbaset-workload:
    parameter_input: quickstart-couchbase-workload.json
    template_file: quickstart-couchbase.template
